# Generated by Django 3.2.9 on 2021-11-25 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0008_program_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='viewers',
            field=models.ManyToManyField(related_name='_program_program_viewers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
